### ISSUE TITLE
[11.0] Bug in the field_image_preview

### ISSUE THREAD

**Issue by satriani-vai** [shurshilov/odoo#2]
Any try to open a product will produce this error.
```
Fehler:
Uncaught TypeError: (this.recordData.__last_update || "").replace is not a function

https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:5335
Zurückverfolgung
TypeError: (this.recordData.__last_update || "").replace is not a function
    at Class._render (https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:5335:451)
    at https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:890:1329
    at https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:681
    at fire (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:796:299)
    at Object.add [as done] (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:797:467)
    at Array.<anonymous> (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:649)
    at Function.each (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:625:767)
    at Object.<anonymous> (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:560)
    at Function.Deferred (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:803:194)
    at Object.then (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:525)
```

**Comment by shurshilov** [comment]
You have skype?and say odoo version17.01.2018, 01:51, "Alex" <notifications@github.com>:Any try to open a product will produce this error.
Fehler:
Uncaught TypeError: (this.recordData.__last_update || "").replace is not a function

https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:5335
Zurückverfolgung
TypeError: (this.recordData.__last_update || "").replace is not a function
    at Class._render (https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:5335:451)
    at https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:890:1329
    at https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:681
    at fire (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:796:299)
    at Object.add [as done] (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:797:467)
    at Array.<anonymous> (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:649)
    at Function.each (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:625:767)
    at Object.<anonymous> (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:560)
    at Function.Deferred (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:803:194)
    at Object.then (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:525)

**Comment by shurshilov** [comment]
soryy, see version 11)) i understand bug, need just delete replece function, interesting wich BROWER you use???17.01.2018, 01:51, "Alex" <notifications@github.com>:Any try to open a product will produce this error.
Fehler:
Uncaught TypeError: (this.recordData.__last_update || "").replace is not a function

https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:5335
Zurückverfolgung
TypeError: (this.recordData.__last_update || "").replace is not a function
    at Class._render (https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:5335:451)
    at https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:890:1329
    at https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:681
    at fire (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:796:299)
    at Object.add [as done] (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:797:467)
    at Array.<anonymous> (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:649)
    at Function.each (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:625:767)
    at Object.<anonymous> (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:560)
    at Function.Deferred (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:803:194)
    at Object.then (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:525)

**Comment by shurshilov** [comment]
BROWSER ?17.01.2018, 15:37, "Артем Шуршилов" <shurshilov.a@yandex.ru>:soryy, see version 11)) i understand bug, need just delete replece function, interesting wich BROWER you use???17.01.2018, 01:51, "Alex" <notifications@github.com>:Any try to open a product will produce this error.
Fehler:
Uncaught TypeError: (this.recordData.__last_update || "").replace is not a function

https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:5335
Zurückverfolgung
TypeError: (this.recordData.__last_update || "").replace is not a function
    at Class._render (https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:5335:451)
    at https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:890:1329
    at https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:681
    at fire (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:796:299)
    at Object.add [as done] (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:797:467)
    at Array.<anonymous> (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:649)
    at Function.each (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:625:767)
    at Object.<anonymous> (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:560)
    at Function.Deferred (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:803:194)
    at Object.then (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:525)

**Comment by shurshilov** [comment]
replace function is standart function, and this part of code is just copy base odoo module, may your browes dont keep this function17.01.2018, 01:51, "Alex" <notifications@github.com>:Any try to open a product will produce this error.
Fehler:
Uncaught TypeError: (this.recordData.__last_update || "").replace is not a function

https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:5335
Zurückverfolgung
TypeError: (this.recordData.__last_update || "").replace is not a function
    at Class._render (https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:5335:451)
    at https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:890:1329
    at https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:681
    at fire (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:796:299)
    at Object.add [as done] (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:797:467)
    at Array.<anonymous> (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:649)
    at Function.each (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:625:767)
    at Object.<anonymous> (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:560)
    at Function.Deferred (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:803:194)
    at Object.then (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:525)

**Comment by shurshilov** [comment]
hmm just odoo developer change 11 version, and my code break.need repleca string on this unique: field_utils.format.datetime(this.recordData.__last_update).replace(/[^0-9]/g, ''),17.01.2018, 01:51, "Alex" <notifications@github.com>:Any try to open a product will produce this error.
Fehler:
Uncaught TypeError: (this.recordData.__last_update || "").replace is not a function

https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:5335
Zurückverfolgung
TypeError: (this.recordData.__last_update || "").replace is not a function
    at Class._render (https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:5335:451)
    at https://www.mysite.com/web/content/1074-f31f66f/web.assets_backend.js:890:1329
    at https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:681
    at fire (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:796:299)
    at Object.add [as done] (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:797:467)
    at Array.<anonymous> (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:649)
    at Function.each (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:625:767)
    at Object.<anonymous> (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:560)
    at Function.Deferred (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:803:194)
    at Object.then (https://www.mysite.com/web/content/1073-1e45acd/web.assets_common.js:802:525)

**Comment by satriani-vai** [comment]
I have applied your last commits, it seems to work very well :+1:
